OLX/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('OLX_main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OLX_main/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.ProductView.as_view(), name='main'),
    path('create/', views.CreateProductView.as_view(), name='create_post'),
    path('datail/<slug:slug>', views.ProductDatailView.as_view(), name='datail'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('category/<slug:slug>/', views.CategoryView.as_view(), name='category'),
    path('comments/<int:pk>/', views.CommentsView.as_view(), name='comments'),
]

OLX_main/models.py
from django.db import models
from django.urls import reverse



class User(models.Model):
    # Пользователь
    name = models.CharField('Имя', max_length=150)
    phone_number = models.CharField(max_length=21, default='')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Category(models.Model):
    # Категории
    name = models.CharField('Название', max_length=70)
    url = models.SlugField(max_length=120, unique=True)
    img = models.ImageField('Картинка', upload_to='photo_category/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

    def get_absolute_url(self):
        return reverse('category', kwargs={'slug' : self.url})


class Product(models.Model):
    # Разные товары
    title = models.CharField('Название', max_length=70)
    description = models.TextField('Описание')
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    poster = models.ImageField('Постер', upload_to='user_product/')
    draft = models.BooleanField('В наличии', default=False)
    url = models.SlugField(max_length=150, unique=True)
    category = models.ForeignKey(
        Category, verbose_name='Категории', on_delete=models.SET_NULL, null=True)
    users = models.ManyToManyField(User, verbose_name='Пользователи', related_name='product_user')
    
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def get_absolute_url(self):
        return reverse('datail', kwargs={'slug' : self.url})


class Comments(models.Model):
    # Коментарий
    name = models.CharField('Имя', max_length=150)
    text = models.TextField('Коментарий', max_length=5000)
    email = models.EmailField()
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Родитель')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукты')

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

OLX_main/forms.py
from .models import *
from django.forms import ModelForm
from django import forms


class AddNewPostForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'description', 'price', 'poster', 'category', 'url']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 5}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'users': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }


class AddComentsForm(forms.ModelForm):
    class Meta:
        app_label = 'django_comments_xtd'
        model = Comments
        fields = ['name', 'text', 'email']

OLX_main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, View
from .models import *
from .forms import *


class CategoryOutput:
    # Вывод категорий
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categoryes'] = Category.objects.all()     
        return context


class ProductView(CategoryOutput, ListView):
    # Вывод товара
    model = Product
    queryset = Product.objects.filter(draft=False)


class ProductDatailView(CategoryOutput, DetailView):
    # полное описание товара
    model = Product
    slug_field = 'url'


class SearchView(CategoryOutput, ListView):
    # поиск по сайту
    def get_queryset(self):
        query = self.request.GET.get('search')
        queryset = Product.objects.filter(title__icontains=query)
        return queryset


class CategoryView(CategoryOutput, ListView):
    # вывод товар по категории
    model = Product
    template_name = 'OLX_main/product_list.html'

    def get_queryset(self):
        category = get_object_or_404(Category, url=self.kwargs['slug'])
        return Product.objects.filter(category=category, draft=False)


class CreateProductView(View):
    # добавление нового обьявления
    def get(self, request):
        form = AddNewPostForm()
        return render(request, 'OLX_main/create_product.html', {'form': form})

    def post(self, request):
        form = AddNewPostForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.save()
            return redirect('main')
        else:
            return render(request, 'OLX_main/create_product.html', {'form': form})


class CommentsView(View):
    # добавление коментария
    def post(self, request, pk):
        form = AddComentsForm(request.POST)
        product = Product.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.product = product
            form.save()
        return redirect(product.get_absolute_url())

OLX_main/templates/OLX_main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'OLX_main/img/olx.png' %}">
    <link rel="stylesheet" href="{% static 'OLX_main/css/index.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header class="header scrolling">
        <form action="{% url 'search' %}" method="get" class="search">
            <input type="search" placeholder="Пошук..." name="search">
            <button type="submit">Знайти</button>
        </form>
        <div class="header-left">
            <!-- Контент расположенный слева -->
            <a href="{% url 'main' %}"><img src="{% static 'OLX_main/img/OLX_blue_logo.png' %}" alt="logo-olx"></a>
        </div>
        <div class="header-right">
            <!-- Контент расположенный справа -->
            <nav>
                <div>
                    <ul>
                        {% if user.is_authenticated %}
                        <p class="user-name">{{ user.username }}</p>
                        <a href="{% url 'account_logout' %}">
                            <li class="add-announcement">Вихід</li>
                        </a>
                        <a href="{% url 'create_post' %}">
                            <li class="add-announcement">Додати оголошення</li>
                        </a>
                        {% else %}
                        <a href="{% url 'account_login' %}">
                            <li class="add-announcement">Вхід</li>
                        </a>
                        <a href="{% url 'account_signup' %}">
                            <li class="add-announcement">Реєстрація</li>
                        </a>
                        <a href="#" onclick="alert('Вы должны зарегистрироваться, прежде чем добавить объявление.')">
                            <li class="add-announcement">Додати оголошення</li>
                        </a>
                        {% endif %}

                    </ul>
                </div>
            </nav>
        </div>
    </header>

    {% block registration %}
    {% endblock %}

    {% block main %}
    {% endblock %}


    {% block footer %}
    <footer id="footer" class="footer-1">
        <div class="main-footer widgets-dark typo-light">
            <div class="container">
                <div class="row">

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget subscribe no-box">
                            <h5 class="widget-title">COMPANY NAME<span></span></h5>
                            <p>Спасибо за просмотр моего ОЛХ сайта. Весь функционал сделай мной и он рабочий. Хорошего
                                вам дня.</p>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget no-box">
                            <h5 class="widget-title">Quick Links<span></span></h5>
                            <ul class="thumbnail-widget">
                                <li>
                                    <div class="thumb-content"><a href="#">Get Started</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">Top Leaders</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">Success Stories</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">Event/Tickets</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">News</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">Lifestyle</a></div>
                                </li>
                                <li>
                                    <div class="thumb-content"><a href="#.">About</a></div>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">
                        <div class="widget no-box">
                            <h5 class="widget-title">Get Started<span></span></h5>
                            <p>Begin
                                Get access to the full functionality of the site after registration.</p>
                            <a class="btn" href="{% url 'account_signup' %}" target="_blank">Register Now</a>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6 col-md-3">

                        <div class="widget no-box">
                            <h5 class="widget-title">Contact Us<span></span></h5>

                            <p><a href="https://github.com/ZhankovVG" title="glorythemes"
                                    style="color: rgb(108, 243, 243);">info.my github</a></p>
                            <ul class="social-footer2">
                                <li class=""><a title="youtube" target="_blank"
                                        href="https://www.youtube.com/channel/UC5wo3B7nxMAzMII8EtLDQLQ"><img
                                            alt="youtube" width="30" height="30"
                                            src="{% static 'OLX_main/img/pngwing.com (5).png' %}"></a></li>
                                <li class=""><a href="https://www.facebook.com/profile.php?id=100025923456368"
                                        target="_blank" title="Facebook"><img alt="Facebook" width="30" height="30"
                                            src="{% static 'OLX_main/img/pngwing.com (6).png' %}"></a></li>
                                <li class=""><a href="#" target="_blank" title="Twitter"><img alt="Twitter" width="30"
                                            height="30" src="{% static 'OLX_main/img/pngwing.com (7).png' %}"></a></li>
                                <li class=""><a title="instagram" target="_blank"
                                        href="https://www.instagram.com/trenirovannyi/?hl=ru"><img alt="instagram"
                                            width="30" height="30"
                                            src="{% static 'OLX_main/img/pngwing.com (8).png' %}"></a></li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <p>Copyright Company OLX © 2023. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const header = document.querySelector('.header');
            let scrollPosition = window.pageYOffset;

            const handleScroll = () => {
                const newScrollPosition = window.pageYOffset;
                if (newScrollPosition > scrollPosition) {
                    header.classList.add('scrolling');
                } else {
                    header.classList.remove('scrolling');
                }
                scrollPosition = newScrollPosition;
            };

            handleScroll();

            window.addEventListener('scroll', handleScroll);
        });
    </script>

</body>

</html>

OLX_main/templates/OLX_main/create_product.html
{% extends 'OLX_main/base.html' %}


{% block title %}
Добавление нового обьявления
{% endblock %}

{% block main %}
<div class="datail-product">
    <h1>Добавление статьй</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }} <br><br>
        <button class="btn btn-warning">Добавить публикацию</button>
    </form>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

OLX_main/templates/OLX_main/product_detail.html
{% extends 'OLX_main/base.html' %}
{% load static %}

{% block title %}
{{ product.title }}
{% endblock %}


{% block main %}
<div class="datail-product">
    <a href="javascript:history.back()" style="float: left;"><i class="bi bi-chevron-left"></i> Назад</a>
    <div class="category-path">
        <a href="{% url 'main' %}">Головна /</a>
        <a href="{% url 'category' product.category.url %}">{{ product.category.name }} /</a>
        <a href="#">{{ product.title | truncatewords:3 }}</a>
        
    </div>
    <hr>
    <div>
        <div class="photo-main-page">

            <img src="{{ product.poster.url }}" alt=""><br><br>
        </div>
        <h3>{{ product.title }}</h3><br>
        <h4>
            <b>
                <p>{{ product.price }} грн.</p>
                <hr>
            </b>
        </h4>
        <b>
            <h4>ОПИС</h4>
        </b>
        <div class="description">
            {{ product.description }}
            
        </div><br>

        {% for user in product.users.all %}
        {% if user.phone_number %}
        <b>Продавець: </b>{{ user.name }} <br>

        <div class="number-phone">
            <p onclick="showPhoneNumber()"><b>Связаться с продавцом</b></p>
            <button id="phone-btn">
                <a href="{{ user.phone_number }}">{{ user.phone_number }}</a></button>
            {% endif %}
            {% endfor %}
            <hr>
        </div>

    </div>
    <div class="comments">
        <form action="{% url 'comments' product.id %}" method="post" class="comment-form">
            <h4>Оставить отзыв о товаре</h4>
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Имя *</label>
                <input type="text" name="name" class="form-control" placeholder="Имя *">
            </div>
            <div class="form-group">
                <label for="useremail">Email *</label>
                <input type="email" name="email" class="form-control" placeholder="Email *">
            </div>
            <div class="form-group">
                <label for="comments">Комментарий *</label>
                <textarea name="text" cols="23" class="form-control" placeholder="Ваш комментарий *"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Отправить</button>
            </div>
        </form>
    </div>
    <div class="comments-user">
        <h4>Коментарии:</h4>
        {% for el in product.comments_set.all %}
        <p><b>Имя :</b> {{ el.name }}</p>
        <p><b>Коментарий :</b> {{ el.text }}</p>
        <hr>
        {% endfor %}
    </div>

</div>

<script>
    function showPhoneNumber() {
        var phoneBtn = document.getElementById("phone-btn");
        phoneBtn.style.display = "block";
    }

    // кнопка назад на предыдущую страницу
    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}

OLX_main/templates/OLX_main/product_list.html
{% extends 'OLX_main/base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block main %}
<div class="centr">
    <h2>Головні рубрики</h2>
</div>
<div class="center-block">
    {% for el in categoryes %}
    <div class="category-column">
        <img src="{{ el.img.url }}" alt="category_img">
        <br>
        <a href="{{ el.get_absolute_url }}">{{ el.name }}</a>
    </div>
    {% endfor %}
</div>

<div class="VIP-centr">
    <h2>VIP-оголошення</h2>
</div>

<!-- start output of products -->

<div class="output_product">
    {% for product in product_list %}
    <div class="product-column">
        <img class="photo" src="{{ product.poster.url }}" alt="photo">
        <br><br>
        <a href="{{ product.get_absolute_url }}">{{ product.title | truncatewords:3  }}</a>
        <br>
        {{ product.price }} грн.
    </div>
    {% endfor %}

<!-- end output of products -->



<div class="btn-up btn-up_hide"></div>

<script>
   const btnUp = {
  el: document.querySelector('.btn-up'),
  scrolling: false,
  show() {
    if (this.el.classList.contains('btn-up_hide') && !this.el.classList.contains('btn-up_hiding')) {
      this.el.classList.remove('btn-up_hide');
      this.el.classList.add('btn-up_hiding');
      window.setTimeout(() => {
        this.el.classList.remove('btn-up_hiding');
      }, 300);
    }
  },
  hide() {
    if (!this.el.classList.contains('btn-up_hide') && !this.el.classList.contains('btn-up_hiding')) {
      this.el.classList.add('btn-up_hiding');
      window.setTimeout(() => {
        this.el.classList.add('btn-up_hide');
        this.el.classList.remove('btn-up_hiding');
      }, 300);
    }
  },
  addEventListener() {
    // при прокрутке окна (window)
    window.addEventListener('scroll', () => {
      const scrollY = window.scrollY || document.documentElement.scrollTop;
      if (this.scrolling && scrollY > 0) {
        return;
      }
      this.scrolling = false;
      // если пользователь прокрутил страницу более чем на 200px
      if (scrollY > 400) {
        // сделаем кнопку .btn-up видимой
        this.show();
      } else {
        // иначе скроем кнопку .btn-up
        this.hide();
      }
    });
    // при нажатии на кнопку .btn-up
    document.querySelector('.btn-up').onclick = () => {
      this.scrolling = true;
      this.hide();
      // переместиться в верхнюю часть страницы
      window.scrollTo({
        top: 0,
        left: 0,
        behavior: 'smooth'
      });
    }
  }
}

btnUp.addEventListener();
</script>
{% endblock %}